// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO3jegfZNbXIVj4Q2wE4yB8ZqcIjz8R3c',
    appId: '1:30461072894:web:ec960b3b543723798b5caf',
    messagingSenderId: '30461072894',
    projectId: 'flutter-prime',
    authDomain: 'flutter-prime.firebaseapp.com',
    storageBucket: 'flutter-prime.appspot.com',
    measurementId: 'G-7MNB062LGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD98HQIOu8FbYGb9bdAsnMIlCfgbS_SwVA',
    appId: '1:30461072894:android:209f48acd6c85d1e8b5caf',
    messagingSenderId: '30461072894',
    projectId: 'flutter-prime',
    storageBucket: 'flutter-prime.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuvLjWgweWQ8qtImFGopgWCQfubsWLyI0',
    appId: '1:30461072894:ios:4f80e76934a4b3728b5caf',
    messagingSenderId: '30461072894',
    projectId: 'flutter-prime',
    storageBucket: 'flutter-prime.appspot.com',
    iosClientId:
        '30461072894-lb8gq4v89b1jcspca7qe9r4dr47g1i8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPrime',
  );
}
